# Generated by Django 3.2.3 on 2021-05-15 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Osoba_kontatowa',
            new_name='contact_person',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Nazwa',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='Zadanie',
            new_name='task_name',
        ),
        migrations.RemoveField(
            model_name='client',
            name='NIP',
        ),
        migrations.RemoveField(
            model_name='client',
            name='Numer_telefonu',
        ),
        migrations.RemoveField(
            model_name='task',
            name='Postep_zadania',
        ),
        migrations.AddField(
            model_name='client',
            name='comments',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='client',
            name='phone_number',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='vat_number',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Serwis', 'Serwis'), ('Czesci', 'Czesci'), ('Maszyna', 'Maszyna')], default='null', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_information', models.CharField(max_length=500)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.task')),
            ],
        ),
    ]
