# Generated by Django 3.2.3 on 2021-05-15 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_alter_client_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='vip',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskprogress',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
